"use client";
import { ChangeEvent, PointerEvent, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Download, ImagePlus, Move, RotateCcw, Upload } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { useArtStore } from "@/components/art-store";
const demoRoom="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=90";
export default function Mockup(){const {artworks}=useArtStore();const list=artworks.filter(a=>a.published);const [selected,setSelected]=useState(list[0]);const [room,setRoom]=useState(demoRoom);const [scale,setScale]=useState(30);const [frame,setFrame]=useState("black");const [pos,setPos]=useState({x:50,y:40});const [drag,setDrag]=useState<{x:number,y:number}|null>(null);const stage=useRef<HTMLDivElement>(null);
const upload=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)setRoom(URL.createObjectURL(f))};const move=(e:PointerEvent<HTMLDivElement>)=>{if(!drag||!stage.current)return;const r=stage.current.getBoundingClientRect();setPos(p=>({x:Math.max(10,Math.min(90,p.x+(e.clientX-drag.x)/r.width*100)),y:Math.max(12,Math.min(85,p.y+(e.clientY-drag.y)/r.height*100))}));setDrag({x:e.clientX,y:e.clientY})};
return <main><SiteHeader/><div className="mockup-head"><Link href="/"><ArrowLeft/> Back to gallery</Link><p className="kicker">Room preview studio</p><h1>Make sure it<br/><em>belongs.</em></h1><p>Choose a work, add your room and find the scale that feels perfect.</p></div><section className="mockup-workspace"><aside><h2><span>01</span>Choose your artwork</h2><div className="mini-art-grid">{list.map(a=><button className={selected?.id===a.id?"selected":""} key={a.id} onClick={()=>setSelected(a)}><img src={a.image} alt=""/><span>{a.title}<small>{a.width} × {a.height} cm</small></span></button>)}</div><h2><span>02</span>Add your room</h2><label className="room-upload"><Upload/><span>Upload a room photo<small>JPG, PNG or WEBP</small></span><input type="file" accept="image/*" onChange={upload}/></label><h2><span>03</span>Finish & scale</h2><div className="frames">{["none","black","white","oak"].map(f=><button className={frame===f?"active":""} onClick={()=>setFrame(f)} key={f}>{f}</button>)}</div><label className="scale-control">Artwork scale <output>{scale}%</output><input type="range" min="12" max="65" value={scale} onChange={e=>setScale(+e.target.value)}/></label></aside><div className="mockup-preview"><div className="mockup-toolbar"><span>Live preview · {selected?.width} × {selected?.height} cm</span><button onClick={()=>{setPos({x:50,y:40});setScale(30)}}><RotateCcw/> Reset</button></div><div className="room-stage" ref={stage} style={{backgroundImage:`url(${room})`}}>{selected&&<div className={`placed-art ${frame}`} style={{left:`${pos.x}%`,top:`${pos.y}%`,width:`${scale}%`,aspectRatio:`${selected.width}/${selected.height}`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag({x:e.clientX,y:e.clientY})}} onPointerMove={move} onPointerUp={()=>setDrag(null)}><img src={selected.image} alt={selected.title}/><i><Move/> drag to position</i></div>}</div><div className="mockup-bottom"><div><ImagePlus/><span>Previewing <strong>{selected?.title}</strong></span></div><button><Download/> Save preview</button></div></div></section></main>}
