"use client";
import Link from "next/link";
import { ArrowDown, ArrowRight, Heart, MoveUpRight, Sparkles } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { useArtStore } from "@/components/art-store";
import { ContactSection } from "@/components/contact-section";
import { WhatsAppBuyButton } from "@/components/whatsapp-buy-button";

export default function Home(){ const {artworks}=useArtStore(); const published=artworks.filter(a=>a.published); const hero=published.find(a=>a.featured)||published[0]; return <main><SiteHeader/>
  <section className="hero">
    <div className="hero-copy"><p className="kicker"><Sparkles/> Curated art, made personal</p><h1>Make space<br/>for <em>feeling.</em></h1><p className="hero-lead">Art shouldn&apos;t just match your room. It should change how the room feels. Discover prints chosen for homes with a point of view.</p><div className="hero-buttons"><a className="button dark" href="#collection">Explore the collection <ArrowRight/></a><Link className="text-link" href="/mockup">Try it on your wall <MoveUpRight/></Link></div><a className="scroll" href="#collection"><ArrowDown/> Scroll to discover</a></div>
    <div className="hero-art" style={{background:hero?.accent||"#ffc4a8"}}>{hero&&<><div className="hero-shape one"/><div className="hero-shape two"/><div className="hero-frame"><img src={hero.image} alt={hero.title}/></div><div className="art-caption"><small>Featured print</small><strong>{hero.title}</strong><span>{hero.artist} · from ${hero.price}</span></div></>}</div>
  </section>
  <section className="marquee"><div>ART FOR SLOW MORNINGS <i>✦</i> PRINTED WITH CARE <i>✦</i> YOUR WALLS, YOUR STORY <i>✦</i> ART FOR SLOW MORNINGS <i>✦</i></div></section>
  <section className="collection" id="collection"><div className="section-head"><div><p className="kicker">The latest edit</p><h2>Pieces with<br/><em>presence.</em></h2></div><p>Selected for their ability to hold attention and transform everyday spaces—without shouting for it.</p></div><div className="filters"><button className="active">All works</button>{[...new Set(published.map(a=>a.category))].map(c=><button key={c}>{c}</button>)}</div>
  <div className="art-grid">{published.map((art,index)=><article id={art.id} className={`art-card card-${index%3}`} key={art.id}><div className="art-image" style={{background:art.accent}}><img src={art.image} alt={art.title}/><button aria-label="Add to favourites"><Heart/></button><Link href="/mockup">View in your room <MoveUpRight/></Link></div><div className="art-meta"><div><h3>{art.title}</h3><p>{art.artist}, {art.year}</p></div><strong>{new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(art.price)}</strong></div><WhatsAppBuyButton title={art.title} price={art.price} artworkId={art.id}/></article>)}</div></section>
  <section className="try-section"><div className="try-photo"><img src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1500&q=90" alt="Art in a bright living room"/><span>40 × 50 cm</span></div><div className="try-copy"><p className="kicker">No more guessing</p><h2>See it.<br/><em>In your space.</em></h2><p>Upload a photo of your room and preview any piece at the size you&apos;re considering. Move it, resize it and find the placement that feels just right.</p><Link className="button coral" href="/mockup">Try the room preview <ArrowRight/></Link><small>No account needed · Your photo stays private</small></div></section>
  <section className="story" id="story"><p className="kicker">Why Zartfy</p><blockquote>“We believe the art you live with should feel less like decoration—and more like a <em>part of you.</em>”</blockquote><div className="values"><div><span>01</span><h3>Curated, never crowded</h3><p>Every work earns its place, selected for quality, feeling and the life it brings to a space.</p></div><div><span>02</span><h3>Made beautifully</h3><p>Archival papers, responsible materials and specialist printing that honours every detail.</p></div><div><span>03</span><h3>Chosen with confidence</h3><p>Our room preview takes uncertainty out of choosing the perfect artwork and size.</p></div></div></section>
  <ContactSection/>
  <footer className="footer"><Link className="logo light" href="/">zartfy<span>.</span></Link><h2>Find the piece<br/>that feels like <em>you.</em></h2><a className="button light-btn" href="#collection">Explore all art <ArrowRight/></a><div className="footer-bottom"><span>© 2026 Zartfy</span><span>Art for expressive homes.</span><Link href="/admin">Admin</Link><Link href="/admin/analytics">Analytics</Link></div></footer>
  </main> }
